apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: vote-app
spec:
  type: NodePort
  selector:
    app: vote
    namespace: vote-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
